apiVersion: v1
kind: Service
metadata:
  name: {{ include "server-chart.fullname" . }}
  labels:
    {{- include "server-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "server-chart.selectorLabels" . | nindent 4 }}
