apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server-chart.fullname" . }}
  labels:
    {{- include "server-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "server-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "server-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
